Remove deprecated drupal_set_message
WidgetsBurritos/d8-studyguide pull request #143
Opened 2021-05-01 14:32 UTC by akramzairig

Replace deprecated drupal_set_message by \Drupal::messenger

2021-05-03 03:41 UTC, WidgetsBurritos requested changes

2021-05-03 03:41 UTC, WidgetsBurritos commented on 4-back-end-development/4.4-essential-apis-form.md
> +    \Drupal::messenger->addMessage($this->t('You are @age years old.', array('@age' => $form_state->getValue('age'))));
Thank you for this.  There does appear to be missing the parenthesis though. This should be: 

```php
\Drupal::messenger()->addMessage($this->t('You are @age years old.', array('@age' => $form_state->getValue('age'))));
```

If you wouldn't mind fixing that, I can move this change along. 

Thank you.

2021-05-03 18:38 UTC, WidgetsBurritos approved these changes
+1. Thank you

2021-05-03 18:38 UTC, merged

2021-05-04 02:21 UTC, akramzairig commented
@WidgetsBurritos  You're welcome , thanks for merging